<?php
return [
    'block',
    'compact',
    'inherit',
    'inline',
    'inline-block',
    'inline-table',
    'list-item',
    'marker',
    'none',
    'run-in',
    'table',
    'table-caption',
    'table-cell',
    'table-column',
    'table-column-group',
    'table-footer-group',
    'table-header-group',
    'table-row',
    'table-row-group',
];
?>