<?php
return [
    'tag' => 'textarea',
    'attr' => [
        'cols' => 80,
        'rows' => 20,
    ],
    'widget' => [
        'options' => [
            'language' => 'lang',
            'toolbar' => 'Custom',
        ],
        'name' => 'kendoEditor',
        'options' => [
            'messages' => [
                "bold" => "Gras",
                "italic" => "Italique",
                "underline" => "Souligné",
                "strikethrough" => "Barré",
                "superscript" => "Exposant",
                "subscript" => "Indice",
                "justifyCenter" => "Centrer le texte",
                "justifyLeft" => "Aligner le texte à gauche",
                "justifyRight" => "Aligner le texte à droite",
                "justifyFull" => "Justifier",
                "insertUnorderedList" => "Insérer une liste",
                "insertOrderedList" => "Insérer une liste ordonnée",
                "indent" => "Vers l'intérieur",
                "outdent" => "Vers l'extérieur",
                "createLink" => "Insérer un lien hypertexte",
                "unlink" => "Supprimer le lien",
                "insertImage" => "Insérer une image",
                "insertHtml" => "Insérer du HTML",
                "fontName" => "Famille de police",
                "fontNameInherit" => "Police par défaut",
                "fontSize" => "Taille de police",
                "fontSizeInherit" => "Taille par défaut",
                "formatBlock" => "Format",
                "style" => "Styles",
                "emptyFolder" => "Dossier vide",
                "uploadFile" => "Envoyer",
                "orderBy" => "Trier par: ",
                "orderBySize" => "Taille",
                "orderByName" => "Nom",
                "invalidFileType" => "Le fichier sélectionné \"{0}\" est invalide. Les formats supportés sont {1}.",
                "deleteFile" => "Êtes-vous sûr \"{0}\"?",
                "overwriteFile" => "Un fichier avec le nom \"{0}\" existe déjà dans ce dossier. Voulez-vous le remplacer?",
                "directoryNotFound" => "Dossier introuvable.",
                "imageWebAddress" => "Adresse Web",
                "imageAltText" => "Texte alternatif",
                "linkWebAddress" => "Adresse Web",
                "linkText" => "Texte",
                "linkToolTip" => "Aide",
                "linkOpenInNewWindow" => "Ouvrir le lien dans une nouvelle fenêtre",
                "dialogInsert" => "Insérer",
                "dialogButtonSeparator" => "ou",
                "dialogCancel" => "Annuler"
            ],
        ]
    ],
];
 